POST http://localhost:3003/api/blogs
Content-Type: application/json

{
"title": "ayo mr white" ,
"author": "wrizz",
"url": "www.wassupbiatch.com",
"likes": "42069",
"userId": "63d1fab8ce6d379c793b922d"
}